// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "UiNumberSlider.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class UiNumberSlider
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for UiNumberSlider 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// UiNumberSlider data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.NumberSliders`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class UiNumberSlider: AutoGenerated.ZAutoGenUiNumberSlider
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'UiNumberSlider' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenUiNumberSlider: Custom.Data.CustomItem
  {
    /// <summary>
    /// NumberSliders as int. <br/>
    /// To get other types use methods such as .Decimal("NumberSliders")
    /// </summary>
    public int NumberSliders => _item.Int("NumberSliders");
  }
}